name: Test and lint
permissions: read-all

on:
  pull_request_target:
    branches:
      - main

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install
        
      - name: Run tests
        run: forge test --fork-url ${{ secrets.ETH_RPC_URL }} -vv
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: forge install
      - run: yarn install --frozen-lockfile
      - run: yarn lint:check