name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install
        
      - name: Run tests
        run: forge test --fork-url ${{ secrets.ETH_RPC_URL }} -vv
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile
      - run: yarn lint:check