name: Tests

on:
  push:
    branches: [ parse-output ]
  pull_request:
    branches: [ parse-output ]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout Results
        uses: actions/checkout@v3
        with:
          ref: results
          path: results

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install
      - run: yarn install --frozen-lockfile
        
      - name: Run tests
        run: yarn test:generate ${{ secrets.ETH_RPC_URL }}

      - name: Process latex
        if: ${{ github.event_name != 'pull_request' }}
        uses: dante-ev/latex-action@latest
        with:
          root_file: results.tex
          compiler: lualatex
          working_directory: results
          args: -interaction=nonstopmode -shell-escape

      - name: Save results
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd results
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '13561405+arr00@users.noreply.github.com'
            git add *.pdf
            git commit -m "Autogenerated pdf"
            git push
          fi

  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile
      - run: yarn lint:check

